name: Maven App Pipeline

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-jave@4
        with:
          distribution: temurin
          java-version: '21'

      - name: Bump patch version
        run: |
          mvn build-helper:parse-version versions:set \
            -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minotrVersion}.${parsedVersion.nextIncrementalVersion}' \
            -DgenerateBackupPoms=false

      - name: Commit bumped version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump patch version [skip ci]
          git push
